spring.application.name=Bioscope
server.port=9099
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Database Configuration

spring.datasource.url=${database_url}
spring.datasource.username=${database_username}
spring.datasource.password=${database_password}

# Hibernate Configuration

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jwt configuration
jwt.secret=${jwt_secret}
jwt.authorities=${jwt_authorities}
jwt.issuer=${jwt_issuer}

#token config

opaque.secret=${opaque_secret}

# aws

cloud.aws.credentials.access-key=${aws_access_key}
cloud.aws.credentials.secret-key=${aws_secret_key}
cloud.aws.region.static=${aws_region}
cloud.aws.stack.auto=false
app.s3.bucket=${aws_bucket_name}

#cloudflare
cloudflare.r2.endpoint=${cloudflare_endpoint}
cloudflare.r2.accessKey=${cloudflare_access_key}
cloudflare.r2.secretKey=${cloudflare_secret_key}
cloudflare.r2.bucket=${r2_bucket_name}

#file in mb
file.max-size=5

# redis
spring.data.redis.host=${redis_host}
spring.data.redis.port=${redis_port}

#jasypt
jasypt.secret=${jasypt_secret}

#razorpay
razorpay.key.id=${razorpay_key_id}
razorpay.key.secret=${razorpay_key_secret}

# email
sendgrid.api-key=${sendgrid_api_key}
sendgrid.from-email=${mail_from}

#URIs
api.uri=${api_url}
ui.uri=${ui_url}