spring.application.name=Bioscope
server.port=9099
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Database Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/bioscope
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Configuration

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jwt configuration
jwt.secret=JWT-SECRET
jwt.expiration=JWT_EXPIRATION
jwt.authorities=JWT-AUTHORITIES
jwt.issuer=www.bioscope.com

# aws

cloud.aws.credentials.access-key=AWS-ACCESS_KEY
cloud.aws.credentials.secret-key=AWS-SECRET_KEY
cloud.aws.region.static=AWS-REGION
cloud.aws.stack.auto=false
app.s3.bucket=AWS-BUCKET-NAME
#file in mb
file.max-size=5

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#jasypt
jasypt.secret=JASYPT-SECRET

#razorpay
razorpay.key.id=RAZORPAY-KEY-ID
razorpay.key.secret=RAZORPAY-KEY-SECRET

# email
sendgrid.api-key=SENDGRID-API-KEY
sendgrid.from-email=SENDGRID-FROM-EMAIL
